import type { ReviewFindingInput } from "../review-rules";

type AIReviewMarkdownInput = {
  summary: string;
  findings: string;
  blockingCount: number;
  nonBlockingCount: number;
  confidenceScore?: number | null;
  prdAlignment?: string | null;
  featureRequestId?: string | null;
};

function formatFindingMarkdown(
  finding: ReviewFindingInput,
  index: number,
): string {
  const label =
    finding.severity === "blocking" ? "🚫 Blocking" : "💡 Non-blocking";
  const location = finding.filePath ? ` (\`${finding.filePath}\`)` : "";

  const lines = [
    `### ${index + 1}. ${label}: ${finding.title}${location}`,
    "",
    `**Category:** ${finding.category}`,
    "",
    finding.description,
  ];

  if (finding.codeSuggestion) {
    lines.push("", "**🤖 Suggested fix:**", "```", finding.codeSuggestion, "```");
  }

  return lines.join("\n");
}

/** Rebuild display markdown from a stored AIReview row when pull_request.reviewComment is missing. */
export function buildReviewMarkdownFromAIReview(input: AIReviewMarkdownInput) {
  const findings = parseReviewFindings(input.findings);
  const prdAware = Boolean(input.featureRequestId);
  const scoreLine =
    typeof input.confidenceScore === "number"
      ? `**Review confidence:** ${input.confidenceScore}/100`
      : null;

  const sections = [
    "## ShipFlow AI Review",
    "",
    prdAware
      ? "_PRD-aware review against acceptance criteria and engineering tasks._"
      : "_Generic code review (no linked PRD found)._",
    "",
    `**Summary:** ${input.summary}`,
    "",
    `**PRD alignment:** ${input.prdAlignment ?? "Not evaluated."}`,
    "",
    ...(scoreLine ? [scoreLine, ""] : []),
    `**Findings:** ${input.blockingCount} blocking · ${input.nonBlockingCount} non-blocking`,
  ];

  if (findings.length === 0) {
    sections.push("", "No issues found. ✅");
  } else {
    sections.push(
      "",
      ...findings.map((finding, index) => formatFindingMarkdown(finding, index)),
    );
  }

  sections.push("", "---", "*Generated by ShipFlow AI*");

  return sections.join("\n");
}

export function isStoredReviewComment(comment: string | null | undefined) {
  if (!comment) {
    return false;
  }

  if (
    comment.startsWith("Review in progress:") ||
    comment.startsWith("Review failed:")
  ) {
    return false;
  }

  return (
    comment.includes("ShipFlow AI Review") ||
    comment.includes("**Summary:**") ||
    comment.includes("**Findings:**") ||
    comment.length > 40
  );
}

export function parseReviewFindings(raw: string): ReviewFindingInput[] {
  try {
    const parsed = JSON.parse(raw) as Array<{
      id?: string;
      severity?: string;
      category?: string;
      title?: string;
      description?: string;
      filePath?: string;
      confidence?: number;
      codeSuggestion?: string;
    }>;

    if (!Array.isArray(parsed)) {
      return [];
    }

    return parsed.flatMap((item, index) => {
      if (!item.title || !item.description) {
        return [];
      }

      const severity: ReviewFindingInput["severity"] =
        item.severity === "blocking" ? "blocking" : "non_blocking";

      return [
        {
          id: item.id ?? `finding-${index + 1}`,
          severity,
          category: item.category ?? "general",
          title: item.title,
          description: item.description,
          filePath: item.filePath,
          confidence: item.confidence,
          codeSuggestion: item.codeSuggestion,
        },
      ];
    });
  } catch {
    return [];
  }
}
