import type { StructuredReview } from "@/features/reviews/types/structured-review";

function formatFinding(
  finding: StructuredReview["findings"][number],
  index: number
) {
  const label =
    finding.severity === "blocking" ? "🚫 Blocking" : "💡 Non-blocking";
  const location = finding.filePath ? ` (\`${finding.filePath}\`)` : "";

  return `### ${index + 1}. ${label}: ${finding.title}${location}

**Category:** ${finding.category}

${finding.description}`;
}

export function formatReviewComment(
  review: StructuredReview,
  options: {
    blockingCount: number;
    nonBlockingCount: number;
    prdAware: boolean;
  }
) {
  const sections = [
    "## ShipFlow AI Review",
    "",
    options.prdAware
      ? "_PRD-aware review against acceptance criteria and engineering tasks._"
      : "_Generic code review (no linked PRD found)._",
    "",
    `**Summary:** ${review.summary}`,
    "",
    `**PRD alignment:** ${review.prdAlignment}`,
    "",
    `**Findings:** ${options.blockingCount} blocking · ${options.nonBlockingCount} non-blocking`,
  ];

  if (review.findings.length === 0) {
    sections.push("", "No issues found. ✅");
  } else {
    sections.push(
      "",
      ...review.findings.map((finding, index) => formatFinding(finding, index))
    );
  }

  if (options.blockingCount > 0) {
    sections.push(
      "",
      "> ⚠️ Blocking issues found — feature status set to **fix needed**."
    );
  } else if (options.prdAware) {
    sections.push(
      "",
      "> ✅ No blocking issues — feature is **awaiting approval**."
    );
  }

  sections.push("", "---", "*Generated by ShipFlow AI*");

  return sections.join("\n");
}
