import type { StructuredReview } from "@/features/reviews/types/structured-review";
import { confidenceLabel } from "@/features/reviews/types/structured-review";

function formatFinding(
  finding: StructuredReview["findings"][number],
  index: number,
) {
  const label =
    finding.severity === "blocking" ? "🚫 Blocking" : "💡 Non-blocking";
  const location = finding.filePath
    ? ` (\`${finding.filePath}${finding.lineStart != null ? `:${finding.lineStart}` : ""}\`)`
    : "";

  const confidenceNote =
    typeof finding.confidence === "number"
      ? `**AI confidence:** ${finding.confidence}%`
      : null;

  const sections = [
    `### ${index + 1}. ${label}: ${finding.title}${location}`,
    "",
    `**Category:** ${finding.category}`,
    "",
    finding.description,
    ...(confidenceNote ? ["", confidenceNote] : []),
  ];

  if (finding.codeSuggestion) {
    const fence =
      finding.filePath && finding.lineStart != null ? "suggestion" : "";
    sections.push(
      "",
      "**🤖 Suggested fix:**",
      "```" + fence,
      finding.codeSuggestion,
      "```",
    );
  }

  return sections.join("\n");
}

export function formatReviewComment(
  review: StructuredReview,
  options: {
    blockingCount: number;
    nonBlockingCount: number;
    confidenceScore?: number;
    prdAware: boolean;
  },
) {
  const score = options.confidenceScore ?? review.confidenceScore;
  const scoreLine =
    typeof score === "number"
      ? `**Review confidence:** ${score}/100 — ${confidenceLabel(score)}`
      : null;

  const sections = [
    "## ShipFlow AI Review",
    "",
    options.prdAware
      ? "_PRD-aware review against acceptance criteria and engineering tasks._"
      : "_Generic code review (no linked PRD found)._",
    "",
    `**Summary:** ${review.summary}`,
    "",
    `**PRD alignment:** ${review.prdAlignment}`,
    "",
    ...(scoreLine ? [scoreLine, ""] : []),
    `**Findings:** ${options.blockingCount} blocking · ${options.nonBlockingCount} non-blocking`,
  ];

  if (review.findings.length === 0) {
    sections.push("", "No issues found. ✅");
  } else {
    sections.push(
      "",
      ...review.findings.map((finding, index) => formatFinding(finding, index)),
    );
  }

  if (options.blockingCount > 0) {
    sections.push(
      "",
      "> ⚠️ Blocking issues found — feature status set to **fix needed**.",
    );
  } else if (options.prdAware) {
    sections.push(
      "",
      "> ✅ No blocking issues — feature is **awaiting approval**.",
    );
  }

  sections.push("", "---", "*Generated by ShipFlow AI*");

  return sections.join("\n");
}
